---
- name: Write VM information
  delegate_to: localhost
  connection: local
  become: false
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_api }}"
    netbox_token: "{{ netbox_api_key }}"
    validate_certs: "{{ netbox_validcert }}"
    data:
      name: "{{ inventory_hostname }}"
      custom_fields:
        ssh_host_key_ecdsa: "{{ ansible_ssh_host_key_ecdsa_public }}"
        ssh_host_key_ed25519: "{{ ansible_ssh_host_key_ed25519_public }}"
        # ssh_host_key_rsa_public: "{{ ansible_ssh_host_key_rsa_public }}"
      tags: "{{ netbox_ci_info.virtual_machine.tags + [inventory_add_tags] }}"
    state: present
