---

- name: Write VM information
  delegate_to: localhost
  connection: local
  become: false
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ inventory_netbox_api }}"
    netbox_token: "{{ inventory_netbox_api_key }}"
    validate_certs: "{{ inventory_netbox_validcert }}"
    data:
      name: "{{ inventory_hostname }}"
      custom_fields: "{{ inventory_custom_fields_mapping | default(omit) }}"
      primary_ip4: "{{ inventory_primary_ipv4 }}"
      tags: "{{ netbox_ci_info.virtual_machine.tags + inventory_add_tags }}"
    state: present
