---

- name: "Fetch VM information from NetBox"
  ansible.builtin.include_tasks: virtual/fetch.yml

- name: "Enumerate VM and write to Netbox"
  ansible.builtin.include_tasks: virtual/machine.yml

- name: "Enumerate VM adapter and write to Netbox - {{ item }}"
  ansible.builtin.include_tasks: virtual/adapter.yml
  loop: "{{ interfaces }}"
  when:
    - hostvars[inventory_hostname]['ansible_%s' | format(item)]['type'] != 'bonding'

- name: "Enumerate VM bond and write to Netbox - {{ item }}"
  ansible.builtin.include_tasks: virtual/adapter.yml
  loop: "{{ interfaces }}"
  when:
    - hostvars[inventory_hostname]['ansible_%s' | format(item)]['type'] == 'bonding'
