---

- name: Get serial number  # noqa: no-changed-when command-instead-of-shell
  become: true
  register: inventory_serial_output
  failed_when: inventory_serial_output.rc != 0
  changed_when: false
  ansible.builtin.shell:
    cmd: "{{ inventory_mb_lookup.serialno }}"

- name: Set serial number (Sample data)
  become: false
  when:
    - ansible_check_mode
  ansible.builtin.set_fact:
    inventory_serial_output: '1ABCD23'

- name: Get Product name  # noqa: no-changed-when command-instead-of-shell
  become: true
  register: inventory_model_output
  failed_when: inventory_model_output.rc != 0
  changed_when: false
  ansible.builtin.shell:
    cmd: "{{ inventory_mb_lookup.model }}"

- name: Set Product Name (Sample data)
  become: false
  when:
    - ansible_check_mode
  ansible.builtin.set_fact:
    inventory_model_output: 'PowerEdge R760xa'

- name: Write CI information
  delegate_to: localhost
  connection: local
  become: false
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_api }}"
    netbox_token: "{{ netbox_api_key }}"
    validate_certs: "{{ netbox_validcert }}"
    data:
      name: "{{ inventory_hostname }}"
      # device_type: "{{ inventory_model_output.stdout | lower | replace(' ', '-') }}"
      custom_fields: "{{ inventory_custom_fields_mapping }}"
      device_type: "{{ inventory_mb_lookup.manufacturer }}_{{ inventory_model_output.stdout | lower | replace(' ', '_') }}"
      primary_ip4: "{{ inventory_primary_ipv4 }}"
      serial: "{{ inventory_serial_output.stdout | default(omit) }}"
      tags: "{{ netbox_ci_info.device.tags + inventory_add_tags }}"
    state: present
