---

- name: "Fetch device information from NetBox"
  ansible.builtin.include_tasks: device/fetch.yml

- name: "Enumerate device and write to Netbox"
  ansible.builtin.include_tasks: device/device.yml

- name: "Enumerate device adapter and write to Netbox - {{ item }}"
  ansible.builtin.include_tasks: device/adapter.yml
  loop: "{{ interfaces }}"
  when:
    - hostvars[inventory_hostname]['ansible_%s' | format(item)]['type'] != 'bonding'

- name: "Enumerate device bond and write to Netbox - {{ item }}"
  ansible.builtin.include_tasks: device/adapter.yml
  loop: "{{ interfaces }}"
  when:
    - hostvars[inventory_hostname]['ansible_%s' | format(item)]['type'] == 'bonding'
